[{"prodID":"101","prodCat":"5","prodCatName":"Estore","prodName":"Cricket Kit","prodDesc":"SG VS 319 Xtreme English Willow Cricket Bat Size SH Mens. SG Ecolite Batting Leg Guard Pads Men's Size., SG Super League Batting Gloves Men's Size. SG Profile Abdominal Guard. SG Super Pak Kit Pak Cricket Bag (large). SS Optipro Cricket Helmet Large Size., Super Test Thigh Guard.","prodPrice":"299","prodImg":"https:\/\/laxmikantbhaskarpandhare.000webhostapp.com\/images\/cricket%20kit.jpg"},
{"prodID":"102","prodCat":"5","prodCatName":"Estore","prodName":"Music Player","prodDesc":"PlayerPro Music Player is another lesser-known music player that should be getting a little more traffic. It is widely used and perfect buy for music lovers.","prodPrice":"499","prodImg":"https:\/\/laxmikantbhaskarpandhare.000webhostapp.com\/images\/music%20player.jpg"},
{"prodID":"103","prodCat":"5","prodCatName":"Estore","prodName":"Mac Products","prodDesc":"New eighth-generation Intel 6‑core and quad-core processors. Up to 32GB of memory for running multiple pro apps. Stunning Retina display with True Tone technology. Touch Bar for working more productively.MacBook Pro elevates the notebook to a whole new level of performance and portability. Wherever your ideas take you, you’ll get there faster than ever with high‑performance processors and memory, advanced graphics, blazing‑fast storage, and more. ","prodPrice":"3000","prodImg":"https:\/\/laxmikantbhaskarpandhare.000webhostapp.com\/images\/Mac%20Book.jpg"},
{"prodID":"104","prodCat":"5","prodCatName":"Estore","prodName":"Kitchen Material","prodDesc":"Granite may have more competition than ever before, but its popularity is still unquestioned. The beautiful, strong surface of granite has a natural grain, which gives each installation a unique look. The downside is the fact that it's porous, which means a yearly sealing is required. Stains should also be wiped up promptly.","prodPrice":"999","prodImg":"https:\/\/laxmikantbhaskarpandhare.000webhostapp.com\/images\/Kitchen%20Material.jpg"},
{"prodID":"105","prodCat":"5","prodCatName":"Estore","prodName":"School Bags","prodDesc":"Two-tone denim and logo-printed detailing give serious style to the MICHAEL Michael Kors Rhea Signature Denim Backpack. Small sized bag; 9-1/2W x 12-1/2H x 5D (width is measured across the bottom of backpack); 2.18 lbs. approx. weight 1L handle; 16-1/2L adjustable straps.","prodPrice":"4000","prodImg":"https:\/\/laxmikantbhaskarpandhare.000webhostapp.com\/images\/School%20bags.jpg"},
{"prodID":"106","prodCat":"5","prodCatName":"Estore","prodName":"Hardware Products","prodDesc":"Hardware Products, focused exclusively on top quality spring manufacturing, leads in creative research and development serving established and emerging industries.","prodPrice":"4000","prodImg":"https:\/\/laxmikantbhaskarpandhare.000webhostapp.com\/images\/Hardware%20Products.jpg"},
{"prodID":"107","prodCat":"5","prodCatName":"Estore","prodName":"Dress Material","prodDesc":"During the colder months, tweed, wool, and cashmere suits are appropriate, as the material not only looks structured and professional but also keeps you warm. During the summer, however, swap these suits out for breathable, lightweight fabrics that will keep you cool without compromising on appearance.","prodPrice":"1500","prodImg":"https:\/\/laxmikantbhaskarpandhare.000webhostapp.com\/images\/Dress%20Material.jpg"},
{"prodID":"108","prodCat":"5","prodCatName":"Estore","prodName":"Flight Booking","prodDesc":"Expedia makes finding cheap flights easy. Select from thousands of flights, airline tickets, and airfare deals worldwide. Expedia Price Gaurantee!","prodPrice":"5000","prodImg":"https:\/\/laxmikantbhaskarpandhare.000webhostapp.com\/images\/Flight%20Booking.jpg"},
{"prodID":"109","prodCat":"5","prodCatName":"Estore","prodName":"Shoes","prodDesc":"Leather construction adds durability. Textured rubber sole prevents slippage. Lace-up closure keeps them secure. Hits just above the ankle.","prodPrice":"150000","prodImg":"https:\/\/laxmikantbhaskarpandhare.000webhostapp.com\/images\/Shoes.jpg"},
{"prodID":"110","prodCat":"5","prodCatName":"Estore","prodName":"Movie Tickets","prodDesc":"Buy movie tickets in advance, find movie times, watch trailers, read movie reviews, and more at Cinema Ticket.","prodPrice":"150000","prodImg":"https:\/\/laxmikantbhaskarpandhare.000webhostapp.com\/images\/Cienma%20Ticket.jpg"}

]
