[{"prodID":"1","prodCat":"4","prodCatName":"Ice_Creams","prodName":"Belgian Chocolate Ice Cream","prodDesc":"Our Belgian chocolate combines rich, velvety chocolate ice cream with finely shaved Belgian chocolate for a uniquely textured experience.","prodPrice":"49","prodImg":"http:\/\/www.nithinkrishna.ga\/Images\/products1.jpg","prodCatName":"Bikes"} ,
{"prodID":"2","prodCat":"4","prodCatName":"Ice_Creams","prodName":"Bourbon Vanilla Bean Truffle","prodDesc":"A classic pairing made even better, enjoy creamy vanilla bean ice cream dotted with chocolate truffles and swirled with spicy Bourbon.","prodPrice":"40","prodImg":"http:\/\/www.nithinkrishna.ga\/Images\/products2.png","prodCatName":"Bikes"} , 
{"prodID":"3","prodCat":"4","prodCatName":"Ice_Creams","prodName":"Butter Pecan Ice Cream","prodDesc":"An American classic, revisited with our passion for singular flavor. We blend spoonful after spoonful of buttery roasted pecans with pure, sweet cream to create a delight like no other","prodPrice":"45","prodImg":"http:\/\/www.nithinkrishna.ga\/Images\/products3.jpg","prodCatName":"Bikes"},
{"prodID":"4","prodCat":"4","prodCatName":"Ice_Creams","prodName":"Caramel Cone Ice Cream","prodDesc":"We balance a creamy blend of caramel ice cream and rich caramel swirls with the sweet crunch of chocolaty cone pieces to create a sweet, harmonious bite.","prodPrice":"50","prodImg":"http:\/\/www.nithinkrishna.ga\/Images\/products4.jpg","prodCatName":"Bikes"},
{"prodID":"5","prodCat":"4","prodCatName":"Ice_Creams","prodName":"Espresso Chocolate Cookie Crumble Ice Cream","prodDesc":"The smooth sophistication of coffee ice cream swirled with cookie crumbles and sprinkled with chocolate espresso flakes; let its bold flavors invigorate your senses.\r\n\r\n","prodPrice":"52","prodImg":"http:\/\/www.nithinkrishna.ga\/Images\/products5.jpg","prodCatName":"Bikes"},
{"prodID":"6","prodCat":"4","prodCatName":"Ice_Creams","prodName":"Irish Cream Brownie","prodDesc":"Irish Cream infused into our ice cream with rich chocolate brownie pieces and a decadent fudge swirl.","prodPrice":"52","prodImg":"http:\/\/www.nithinkrishna.ga\/Images\/products6.png","prodCatName":"Bikes"},
{"prodID":"7","prodCat":"4","prodCatName":"Ice_Creams","prodName":"Java Chip Ice Cream","prodDesc":"Rich, sweet chocolaty chips balance our full-bodied coffee ice cream in this delicious homage to one of life's most perfect pairings\r\n\r\n","prodPrice":"51","prodImg":"http:\/\/www.nithinkrishna.ga\/Images\/products7.jpg","prodCatName":"Bikes"},
{"prodID":"8","prodCat":"4","prodCatName":"Ice_Creams","prodName":"Midnight Cookies and Cream Ice Cream","prodDesc":"Dedicated to the serious chocolate lover, our Midnight Cookies and Cream combines chocolate fudge swirls, decadent dark chocolate cookie pieces and creamy dark chocolate ice cream","prodPrice":"59","prodImg":"http:\/\/www.nithinkrishna.ga\/Images\/products8.jpg","prodCatName":"Bikes"},
{"prodID":"9","prodCat":"4","prodCatName":"Ice_Creams","prodName":"White Chocolate Raspberry Truffle Ice Cream","prodDesc":"A truly exquisite ice cream inspired by fine chocolate truffles. We begin with pure white chocolate ice cream and swirl in satisfying chunks of chocolaty fudge truffles and a tangy raspberry ribbon","prodPrice":"60","prodImg":"http:\/\/www.nithinkrishna.ga\/Images\/products9.png","prodCatName":"Bikes"},
{"prodID":"10","prodCat":"4","prodCatName":"Ice_Creams","prodName":"Rum Tres Leches","prodDesc":"A Latin American inspired indulgence, we infuse smooth white Rum into our ice cream then add thick ribbons of dulce de leche and chunks of sweet Tres Leches cake.","prodPrice":"56","prodImg":"http:\/\/www.nithinkrishna.ga\/Images\/products10.jpg","prodCatName":"Bikes"}



]